<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">This Privacy Policy applies to all matters relating to the handling of personal information on the &ldquo;Diversity Eikaiwa&rdquo; website, located at http://diversityeikaiwa.com/which is operated by Rivera Oliver(Hereinafter referred to as the "</span><span style="font-family: 游明朝, serif; color: black;">当社</span><span style="color: black;">").</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">１　</span><span style="color: black;">Basic Policy</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑴　</span><span style="color: black;">It is our top priority to comply with all applicable laws , regulations and guidelines related to our business, concerning privacy protection in handling your personal information.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑵　</span><span style="color: black;">We at all times will take responsibility for protection of personal information and development in our systems to a designated officer in order to help ensure appropriate management and security of personal information.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑶</span><span style="color: black;">We will maintain appropriate actions and safety measures to protect your personal information from improper disclosure or modification and from unauthorized access.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑷</span><span style="color: black;">We will regularly review this Privacy Policy to help ensure that appropriate security are maintained.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑸</span><span style="color: black;">We will respond appropriately to the requests from our users to disclose the personal information that we maintain concerning them, to correct any mistakes in such information and to cease use of their personal information.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">２　</span><span style="color: black;">Collection of personal information</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑴</span><span style="color: black;">We will only collect personal information by appropriate and fair means of the user.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑵　</span><span style="color: black;">Personal information we collect are Name, E-mail, Address, Phone number, interest of the student and Skype ID,etc.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">Information voluntarily provided by you during a lesson or personal contact with a tutor outside of a lesson will not be considered as information collected by us.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">３　</span><span style="color: black;"> use</span><span style="font-family: 游明朝, serif; color: black;">　</span><span style="color: black;">of personal information</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑴</span><span style="color: black;">We will not use the personal information we have obtained in any way that may encourage or facilitate illegal or unjust acts.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑵</span><span style="color: black;">Information we collect may be used for the following reasons:</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<ul style="margin-bottom: 0cm; margin-top: 0px;">
<li style="text-align: left; margin: 0cm 0cm 0.0001pt 0px; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">carry out marketing and business activities related to our services (online education services).</span></li>
</ul>
<p style="text-align: left; text-indent: 10.5pt; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt 21pt; text-align: left; text-indent: -10.5pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">②</span><span style="color: black;">Efforts to improve our service based on your interest including sending questionnaires, or base from your comments and opinions (No information will be disclosed to a third party) </span></p>
<p style="margin: 0cm 0cm 0.0001pt 21pt; text-align: left; text-indent: -10.5pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; text-indent: 10.5pt; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">③</span><span style="color: black;">Processing students/clients/customers application on our website.</span></p>
<p style="text-align: left; text-indent: 10.5pt; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; text-indent: 10.5pt; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">④</span><span style="color: black;">Response to an inquiry or complaint.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑶　</span><span style="color: black;">Before using you personal information other than mentioned above, we will make sure to notify you first and request for your confirmation. We will not use your personal information for other purpose unless you give your consent.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑷　</span><span style="color: black;">The Company may change the purpose of use to the extent that it is reasonably recognized to be related to the current purpose of use. In the event that the purpose of use is changed, the Company will announce the changed content on its website.</span></p>
<p style="margin: 0cm 0cm 11.25pt; text-indent: 10.5pt; font-size: 12pt; font-family: 'MS PGothic', sans-serif;"><span style="font-size: 10.5pt; font-family: Calibri; color: black;">(5) To provide teachers with online English education services and to perform these services in an appropriate and smooth manner.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">４　</span><span style="color: black;">Providing information to third parties</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑴　</span><span style="color: black;">Except in the following cases, we will not, in principle, provide your personal information, cookies, IP addresses, session information, and other non-personally identifiable information to third parties (including third parties located in foreign countries) without your consent.:</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">①</span><span style="color: black;">When it falls under each item of Article 23, Paragraph 1 of </span><span style="font-family: 游明朝, serif; color: black;">個人情報保護法</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: Arial; color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">②</span><span style="color: black;">When we take necessary actions, including legal actions.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">③</span><span style="color: black;">When disclosure is required by law or by a valid order of a court, police department, or other public institution.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑵</span><span style="color: black;">In the event that all or part of the handling of personal information is outsourced, appropriate and necessary measures will be taken to protect the personal information.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑶　</span><span style="color: black;">we are using &ldquo;Session&rdquo;</span><span style="font-family: 游明朝, serif; color: black;">　</span><span style="color: black;">or</span><span style="font-family: 游明朝, serif; color: black;">　&ldquo;</span><span style="color: black;">Cookie</span><span style="font-family: 游明朝, serif; color: black;">&rdquo;</span><span style="color: black;"> to manage access to our website and facilitate effective site administration. </span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">５　</span><span style="color: black;">Security</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">⑴</span><span style="color: black;">We have established appropriate electronic and physical procedures to safeguard personal information of you. We are making sure that we are checking our policies, system and electronics occasionally to maintain high security and up to the standards of our privacy policy.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">６　</span><span style="color: black;">Accountability</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">We have appointed an officer to secure privacy of you. We are also regularly consulting our legal advisor to ensure all procedures are abiding the law.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">７</span><span style="color: black;">Suspension of Use</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">If the information was collected in the improper way that resulted to the user to request to stop using his/her information, we will take necessary investigation and fact check to validate the request of the student/client.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">８</span><span style="color: black;">Requests for correction, addition, deletion, cessation of use, cessation of provision to third parties, and notification of purpose of use of personal information, and requests for disclosure of personal information or records provided to third parties</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">Steps:</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">①</span><span style="color: black;">Email us at diversityeikaiwa2021@gmail.com or at customer.support@diversityeikaiwa.com</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">②</span><span style="color: black;">Write down your complete name, address, phone number and concerns in detail.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">③</span><span style="color: black;">Wait for our response or call with regards to the next step.</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="font-family: 游明朝, serif; color: black;">９　</span><span style="color: black;">Inquiries or Complaints</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">We have established an email and phone number to respond to any inquiries or complaints concerning our handling of personal information. </span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">1. Email: Email us at diversityeikaiwa2021@gmail.com or at customer.support@diversityeikaiwa.com</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">2. Phone: 03 6202 7083</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">3. Address: 103-0023 </span><span style="font-family: 游明朝, serif; color: black;">東京中央区日本橋本町３－</span><span style="color: black;">3</span><span style="font-family: 游明朝, serif; color: black;">－</span><span style="color: black;">6</span><span style="font-family: 游明朝, serif; color: black;">ワカ末ビル</span><span style="color: black;"> 7 </span><span style="font-family: 游明朝, serif; color: black;">階</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">&nbsp;</span></p>
<p style="text-align: left; margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri;"><span style="color: black;">4 Representative responsible for personal information</span></p>
<p><span style="font-size: 10.5pt; font-family: 游明朝, serif; color: black;">　個人情報取扱いに関する代表責任者　</span><span style="font-size: 10.5pt; font-family: Calibri; color: black;">Rivera Oliver</span></p>